# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ExtractDataDesign.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-4, -1, 811, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, -1, 781, 521))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.maxTrhL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.maxTrhL.setObjectName("maxTrhL")
        self.gridLayout.addWidget(self.maxTrhL, 1, 2, 1, 1)
        self.loadCalibImageBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.loadCalibImageBtn.setObjectName("loadCalibImageBtn")
        self.gridLayout.addWidget(self.loadCalibImageBtn, 3, 0, 1, 1)
        self.minTrhL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.minTrhL.setObjectName("minTrhL")
        self.gridLayout.addWidget(self.minTrhL, 0, 2, 1, 1)
        self.maxTrhSld = QtWidgets.QSlider(self.gridLayoutWidget)
        self.maxTrhSld.setMaximum(255)
        self.maxTrhSld.setOrientation(QtCore.Qt.Horizontal)
        self.maxTrhSld.setObjectName("maxTrhSld")
        self.gridLayout.addWidget(self.maxTrhSld, 1, 1, 1, 1)
        self.blurSld = QtWidgets.QSlider(self.gridLayoutWidget)
        self.blurSld.setMinimum(1)
        self.blurSld.setMaximum(10)
        self.blurSld.setOrientation(QtCore.Qt.Horizontal)
        self.blurSld.setObjectName("blurSld")
        self.gridLayout.addWidget(self.blurSld, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.minTrhSld = QtWidgets.QSlider(self.gridLayoutWidget)
        self.minTrhSld.setMaximum(255)
        self.minTrhSld.setOrientation(QtCore.Qt.Horizontal)
        self.minTrhSld.setObjectName("minTrhSld")
        self.gridLayout.addWidget(self.minTrhSld, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 0, 1, 1)
        self.blurL = QtWidgets.QLabel(self.gridLayoutWidget)
        self.blurL.setObjectName("blurL")
        self.gridLayout.addWidget(self.blurL, 2, 2, 1, 1)
        self.calibrateBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.calibrateBtn.setObjectName("calibrateBtn")
        self.gridLayout.addWidget(self.calibrateBtn, 4, 0, 1, 1)
        self.sourceImageView = QtWidgets.QLabel(self.gridLayoutWidget)
        self.sourceImageView.setText("")
        self.sourceImageView.setObjectName("sourceImageView")
        self.gridLayout.addWidget(self.sourceImageView, 3, 1, 2, 1)
        self.destImageView = QtWidgets.QLabel(self.gridLayoutWidget)
        self.destImageView.setText("")
        self.destImageView.setObjectName("destImageView")
        self.gridLayout.addWidget(self.destImageView, 3, 2, 2, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout.setRowStretch(3, 10)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 781, 521))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setVerticalSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.blurL_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.blurL_2.setObjectName("blurL_2")
        self.gridLayout_2.addWidget(self.blurL_2, 2, 2, 1, 1)
        self.blurSld_2 = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.blurSld_2.setMinimum(1)
        self.blurSld_2.setMaximum(10)
        self.blurSld_2.setOrientation(QtCore.Qt.Horizontal)
        self.blurSld_2.setObjectName("blurSld_2")
        self.gridLayout_2.addWidget(self.blurSld_2, 2, 1, 1, 1)
        self.maxTrhSld_2 = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.maxTrhSld_2.setMaximum(255)
        self.maxTrhSld_2.setOrientation(QtCore.Qt.Horizontal)
        self.maxTrhSld_2.setObjectName("maxTrhSld_2")
        self.gridLayout_2.addWidget(self.maxTrhSld_2, 1, 1, 1, 1)
        self.maxTrhL_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.maxTrhL_2.setObjectName("maxTrhL_2")
        self.gridLayout_2.addWidget(self.maxTrhL_2, 1, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 1, 0, 1, 1)
        self.loadLaserImagesBtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.loadLaserImagesBtn.setObjectName("loadLaserImagesBtn")
        self.gridLayout_2.addWidget(self.loadLaserImagesBtn, 3, 0, 1, 1)
        self.minTrhL_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.minTrhL_2.setObjectName("minTrhL_2")
        self.gridLayout_2.addWidget(self.minTrhL_2, 0, 2, 1, 1)
        self.minTrhSld_2 = QtWidgets.QSlider(self.gridLayoutWidget_2)
        self.minTrhSld_2.setMaximum(255)
        self.minTrhSld_2.setOrientation(QtCore.Qt.Horizontal)
        self.minTrhSld_2.setObjectName("minTrhSld_2")
        self.gridLayout_2.addWidget(self.minTrhSld_2, 0, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_2.addWidget(self.spinBox, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.savePositionBtn = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.savePositionBtn.setObjectName("savePositionBtn")
        self.gridLayout_2.addWidget(self.savePositionBtn, 5, 0, 1, 1)
        self.sourceImageView_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.sourceImageView_2.setText("")
        self.sourceImageView_2.setObjectName("sourceImageView_2")
        self.gridLayout_2.addWidget(self.sourceImageView_2, 3, 1, 3, 1)
        self.destImageView_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.destImageView_2.setText("")
        self.destImageView_2.setObjectName("destImageView_2")
        self.gridLayout_2.addWidget(self.destImageView_2, 3, 2, 3, 1)
        self.gridLayout_2.setColumnStretch(0, 1)
        self.gridLayout_2.setColumnStretch(1, 2)
        self.gridLayout_2.setColumnStretch(2, 2)
        self.gridLayout_2.setRowStretch(3, 10)
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.maxTrhSld.valueChanged['int'].connect(self.maxTrhL.setNum)
        self.minTrhSld.valueChanged['int'].connect(self.minTrhL.setNum)
        self.blurSld.valueChanged['int'].connect(self.blurL.setNum)
        self.minTrhSld_2.valueChanged['int'].connect(self.minTrhL_2.setNum)
        self.maxTrhSld_2.valueChanged['int'].connect(self.maxTrhL_2.setNum)
        self.blurSld_2.valueChanged['int'].connect(self.blurL_2.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Extract Data"))
        self.maxTrhL.setText(_translate("MainWindow", "0"))
        self.loadCalibImageBtn.setText(_translate("MainWindow", "Load calibration image"))
        self.minTrhL.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Blur"))
        self.label_7.setText(_translate("MainWindow", "Max threshold"))
        self.label_8.setText(_translate("MainWindow", "Min threshold"))
        self.blurL.setText(_translate("MainWindow", "1"))
        self.calibrateBtn.setText(_translate("MainWindow", "Calibrate image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Calibration"))
        self.blurL_2.setText(_translate("MainWindow", "1"))
        self.maxTrhL_2.setText(_translate("MainWindow", "0"))
        self.label_9.setText(_translate("MainWindow", "Blur"))
        self.label_10.setText(_translate("MainWindow", "Max threshold"))
        self.loadLaserImagesBtn.setText(_translate("MainWindow", "Load images"))
        self.minTrhL_2.setText(_translate("MainWindow", "0"))
        self.label_11.setText(_translate("MainWindow", "Min threshold"))
        self.savePositionBtn.setText(_translate("MainWindow", "Save position"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Images"))
